### ISSUE TITLE
从V2看到楼主项目过来，非常实用的功能，准备部署到工作环境中把邮件归类，谢谢作者

### ISSUE THREAD

**Issue by fox85** [k8scat/ForMaiR#1]
从V2看到楼主项目过来，非常实用的功能，准备部署到工作环境中把邮件归类，谢谢作者 👍

**Comment by k8scat** [comment]
哈哈哈哈，喜欢可以点个Star

**Comment by fox85** [comment]
已点 💯 

另外想请教一下，正则内怎么匹配多个关键字，比如我想在把几个关键字“发票”，“增值税”类似的字眼以一个正则的表达式来写的话应该是怎么写的？

**Comment by k8scat** [comment]
感谢关注本项目！

subject: ".*(发票|增值税).*"
content: ".*(发票|增值税).*"

```python
re.match(r'.*(发票|增值税).*', '这是发票')
```

**Comment by fox85** [comment]
谢谢

我尝试运行时报错，请楼主帮忙看看

root@debian:~/ForMaiR# python3 main.py config.yaml
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from formair.forward import forward_emails
  File "/root/ForMaiR/formair/forward.py", line 4, in <module>
    from formair import pop3, smtp
  File "/root/ForMaiR/formair/pop3.py", line 9, in <module>
    from formair.utils import generate_attachment
  File "/root/ForMaiR/formair/utils.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by k8scat** [comment]
需要安装 `PyYaml` 依赖

```bash
pip install PyYaml
```

**Comment by fox85** [comment]
谢谢！

请问是否只支持POP3？ IMAP支持吗？

**Comment by k8scat** [comment]
> 谢谢！
> 
> 请问是否只支持POP3？ IMAP支持吗？

目前不支持 IMAP

**Comment by fox85** [comment]
好的，请问会计划支持吗

**Comment by fox85** [comment]
re.match(r'.*(发票|增值税).*', '这是发票')

请问楼主，这一行配置是什么意思，如何使用的？在相关文档内没找到说明，谢谢

**Comment by k8scat** [comment]
> re.match(r'._(发票|增值税)._', '这是发票')
> 
> 请问楼主，这一行配置是什么意思，如何使用的？在相关文档内没找到说明，谢谢

不是配置，是正则示例
